<a href="https://colab.research.google.com/github/hamsa-nk/logistics-data-analysis/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

df = pd.read_csv("cleaned_delivery_logistics.csv")

print(df.head())
print(df.shape)
print(df.info())

   delivery_id delivery_partner      package_type vehicle_type delivery_mode  \
0       250.99        delhivery  automobile parts         bike      same day
1       250.99       xpressbees         cosmetics       ev van       express
2       250.99        shadowfax         groceries        truck       two day
3       250.99              dhl       electronics       ev van      same day
4       250.99              dhl          clothing          van       two day

    region weather_condition  distance_km  package_weight_kg  \
0     west             clear        297.0              46.96
1  central              cold         89.6              47.39
2     east             rainy        273.5              26.89
3     east              cold        269.7              12.69
4    north             foggy        256.7              37.02

   delivery_time_hours  expected_time_hours delayed delivery_status  \
0                    8                    8      no       delivered
1                    2                    3      no       delivered
2                   10                   16      no       delivered
3                    6                    8      no       delivered
4                    9                   16      no       delivered

   delivery_rating  delivery_cost  delay_hours delay_status
0                3      1632.7206            0      On Time
1                5       640.1700           -1      On Time
2                4      1448.1700           -6      On Time
3                3      1486.5700           -2      On Time
4                4      1394.5600           -7      On Time
(25000, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  int64
 10  expected_time_hours  25000 non-null  int64
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
 15  delay_hours          25000 non-null  int64
 16  delay_status         25000 non-null  object
dtypes: float64(4), int64(4), object(9)
memory usage: 3.2+ MB
None

In [15]:
print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
delay_hours            0
delay_status           0
dtype: int64
Duplicates: 0

In [16]:
print("Unique delivery IDs:", df["delivery_id"].nunique())
print(df["delivery_time_hours"].describe())
print("\nDelivery Partners:")
print(df["delivery_partner"].unique())

print("\nVehicle Types:")
print(df["vehicle_type"].unique())

print("\nDelivery Modes:")
print(df["delivery_mode"].unique())

print("\nWeather Conditions:")
print(df["weather_condition"].unique())

Unique delivery IDs: 24502
count    25000.000000
mean         6.248040
std          3.140935
min          0.000000
25%          4.000000
50%          6.000000
75%          8.000000
max         19.000000
Name: delivery_time_hours, dtype: float64

Delivery Partners:
['delhivery' 'xpressbees' 'shadowfax' 'dhl' 'amazon logistics' 'blue dart'
 'fedex' 'ecom express' 'ekart']

Vehicle Types:
['bike' 'ev van' 'truck' 'van' 'ev bike' 'scooter']

Delivery Modes:
['same day' 'express' 'two day' 'standard']

Weather Conditions:
['clear' 'cold' 'rainy' 'foggy' 'hot' 'stormy']

In [17]:
print(
    df[
        [
            "distance_km",
            "package_weight_kg",
            "delivery_time_hours",
            "expected_time_hours",
            "delivery_cost",
            "delay_hours"
        ]
    ].corr()
)

                     distance_km  package_weight_kg  delivery_time_hours  \
distance_km             1.000000           0.002311             0.685883
package_weight_kg       0.002311           1.000000             0.001242
delivery_time_hours     0.685883           0.001242             1.000000
expected_time_hours     0.045236           0.001442             0.039755
delivery_cost           0.990772           0.099479             0.678911
delay_hours             0.224596          -0.000867             0.351996

                     expected_time_hours  delivery_cost  delay_hours
distance_km                     0.045236       0.990772     0.224596
package_weight_kg               0.001442       0.099479    -0.000867
delivery_time_hours             0.039755       0.678911     0.351996
expected_time_hours             1.000000      -0.025480    -0.921268
delivery_cost                  -0.025480       1.000000     0.288125
delay_hours                    -0.921268       0.288125     1.000000

In [18]:
print("Zero-hour deliveries:", (df["delivery_time_hours"] == 0).sum())
print(df["delivery_time_hours"].value_counts().sort_index())

Zero-hour deliveries: 255
delivery_time_hours
0      255
1      963
2     1668
3     2352
4     2571
5     3011
6     3118
7     2921
8     2386
9     1875
10    1371
11    1039
12     649
13     371
14     247
15     116
16      51
17      26
18       7
19       3
Name: count, dtype: int64

In [19]:
print(
    df.groupby("vehicle_type")["delivery_time_hours"]
      .mean()
      .sort_values()
)

vehicle_type
ev bike    6.197013
truck      6.217129
ev van     6.250000
van        6.267972
bike       6.277644
scooter    6.278869
Name: delivery_time_hours, dtype: float64

In [20]:
# 1. Repeated IDs
print(df["delivery_id"].value_counts().head(10))

# 2. Zero-hour deliveries
print("Zero-hour deliveries:", (df["delivery_time_hours"] == 0).sum())

# 3. Delivery time distribution
print(df["delivery_time_hours"].value_counts().sort_index())

# 4. Average delivery time by vehicle
print(
    df.groupby("vehicle_type")["delivery_time_hours"]
      .mean()
      .sort_values()
)

# 5. Average delivery time by delivery mode
print(
    df.groupby("delivery_mode")["delivery_time_hours"]
      .mean()
      .sort_values()
)

delivery_id
24750.01    250
250.99      250
16591.00      1
16590.00      1
16589.00      1
16588.00      1
16587.00      1
16586.00      1
16585.00      1
16584.00      1
Name: count, dtype: int64
Zero-hour deliveries: 255
delivery_time_hours
0      255
1      963
2     1668
3     2352
4     2571
5     3011
6     3118
7     2921
8     2386
9     1875
10    1371
11    1039
12     649
13     371
14     247
15     116
16      51
17      26
18       7
19       3
Name: count, dtype: int64
vehicle_type
ev bike    6.197013
truck      6.217129
ev van     6.250000
van        6.267972
bike       6.277644
scooter    6.278869
Name: delivery_time_hours, dtype: float64
delivery_mode
express     6.230868
standard    6.237472
same day    6.244784
two day     6.278642
Name: delivery_time_hours, dtype: float64

In [21]:
print(df["expected_time_hours"].describe())

print("\nExpected time values:")
print(df["expected_time_hours"].value_counts().sort_index())

print("\nExpected vs actual:")
print(
    df[["expected_time_hours", "delivery_time_hours"]]
    .head(20)
)
print(
    df.groupby("expected_time_hours")["delivery_time_hours"]
      .mean()
)

count    25000.000000
mean        13.107680
std          7.559024
min          2.000000
25%          8.000000
50%          8.000000
75%         16.000000
max         24.000000
Name: expected_time_hours, dtype: float64

Expected time values:
expected_time_hours
2     1015
3     1029
4     1037
5     1080
6     1013
7     1051
8     6287
16    6302
24    6186
Name: count, dtype: int64

Expected vs actual:
    expected_time_hours  delivery_time_hours
0                     8                    8
1                     3                    2
2                    16                   10
3                     8                    6
4                    16                    9
5                     2                    4
6                     8                    6
7                     8                    4
8                     8                    5
9                     8                    3
10                    8                    5
11                   16                    3
12                   16                    8
13                    2                    6
14                   16                   12
15                    6                    8
16                   24                   10
17                   24                   11
18                    8                    4
19                    3                    7
expected_time_hours
2     3.102463
3     4.282799
4     5.593057
5     6.871296
6     8.000000
7     9.403425
8     6.248449
16    6.278642
24    6.237472
Name: delivery_time_hours, dtype: float64

In [22]:
zero_deliveries = df[df["delivery_time_hours"] == 0]

print(zero_deliveries)
print(zero_deliveries.shape)

print(
    zero_deliveries[
        [
            "distance_km",
            "package_weight_kg",
            "vehicle_type",
            "delivery_mode",
            "region",
            "weather_condition",
            "delivery_status"
        ]
    ].head(20)
)
print(
    zero_deliveries[
        [
            "distance_km",
            "package_weight_kg"
        ]
    ].describe()
)

       delivery_id  delivery_partner   package_type vehicle_type  \
87          250.99             ekart      furniture          van
136         250.99         shadowfax      groceries      ev bike
181         250.99         blue dart       pharmacy        truck
303         304.00      ecom express      cosmetics         bike
574         575.00         delhivery  fragile items         bike
...            ...               ...            ...          ...
24761     24750.01  amazon logistics      groceries      ev bike
24796     24750.01      ecom express      furniture          van
24876     24750.01  amazon logistics    electronics         bike
24877     24750.01             fedex      cosmetics          van
24963     24750.01         shadowfax      furniture         bike

      delivery_mode   region weather_condition  distance_km  \
87          two day    south              cold          3.6
136        same day     west               hot          8.7
181        same day     east               hot          9.9
303        same day     east               hot         21.0
574         express     east             clear         41.7
...             ...      ...               ...          ...
24761      standard     west              cold         20.5
24796      same day  central             clear         24.5
24876       express     west               hot          8.5
24877      same day  central             clear          8.7
24963      standard    south             clear         10.2

       package_weight_kg  delivery_time_hours  expected_time_hours delayed  \
87                  8.75                    0                   16      no
136                33.93                    0                    8      no
181                30.24                    0                    8      no
303                 8.00                    0                    8      no
574                27.97                    0                    2      no
...                  ...                  ...                  ...     ...
24761              44.44                    0                   24      no
24796              33.00                    0                    8      no
24876              12.90                    0                    2      no
24877              20.49                    0                    8      no
24963              33.23                    0                   24      no

      delivery_status  delivery_rating  delivery_cost  delay_hours  \
87          delivered                3        95.6674          -16
136         delivered                5       245.2900           -8
181         delivered                3       240.2200           -8
303         delivered                4       229.0000           -8
574         delivered                5       342.4100           -2
...               ...              ...            ...          ...
24761       delivered                4       235.8200          -24
24796       delivered                5       321.5000           -8
24876       delivered                5       131.2000           -2
24877       delivered                5       204.9700           -8
24963       delivered                4       150.6900          -24

      delay_status
87         On Time
136        On Time
181        On Time
303        On Time
574        On Time
...            ...
24761      On Time
24796      On Time
24876      On Time
24877      On Time
24963      On Time

[255 rows x 17 columns]
(255, 17)
      distance_km  package_weight_kg vehicle_type delivery_mode   region  \
87            3.6               8.75          van       two day    south
136           8.7              33.93      ev bike      same day     west
181           9.9              30.24        truck      same day     east
303          21.0               8.00         bike      same day     east
574          41.7              27.97         bike       express     east
823          13.2              26.57       ev van      same day    north
836          24.5              35.61         bike       two day  central
871          33.3              48.50       ev van      same day  central
947           9.0               5.43      scooter      standard     west
1046         10.5              33.60      scooter      same day  central
1060         24.7              44.74         bike       express  central
1103         43.0              41.57      scooter       express     west
1109          3.6               3.35          van       two day    south
1292         20.5               4.43      scooter       express  central
1528         14.4              14.59        truck       two day    north
1757         19.9               7.35        truck      standard     east
1773          3.6              21.41          van       express     west
1837          3.6              11.41       ev van      same day     west
2165         28.4              49.52          van      standard    north
2433         20.6              35.56          van      standard    south

     weather_condition delivery_status
87                cold       delivered
136                hot       delivered
181                hot       delivered
303                hot       delivered
574              clear       delivered
823               cold       delivered
836               cold       delivered
871                hot       delivered
947                hot       delivered
1046             clear       delivered
1060               hot       delivered
1103               hot       delivered
1109             clear       delivered
1292              cold       delivered
1528             clear       delivered
1757               hot       delivered
1773             clear       delivered
1837              cold       delivered
2165             clear       delivered
2433             clear       delivered
       distance_km  package_weight_kg
count   255.000000         255.000000
mean     15.386275          26.181098
std      10.617910          14.664126
min       3.600000           0.670000
25%       6.250000          13.465000
50%      13.400000          27.990000
75%      21.950000          38.260000
max      47.000000          49.520000

In [23]:
df_model = df[df["delivery_time_hours"] > 0].copy()

print("Original rows:", len(df))
print("Rows after removing 0-hour records:", len(df_model))
print("Removed rows:", len(df) - len(df_model))

Original rows: 25000
Rows after removing 0-hour records: 24745
Removed rows: 255

In [24]:
df_model = df[df["delivery_time_hours"] > 0].copy()

print("Original rows:", len(df))
print("Rows after cleaning:", len(df_model))
print("Removed rows:", len(df) - len(df_model))

Original rows: 25000
Rows after cleaning: 24745
Removed rows: 255

In [25]:
features = [
    "delivery_partner",
    "package_type",
    "vehicle_type",
    "delivery_mode",
    "region",
    "weather_condition",
    "distance_km",
    "package_weight_kg"
]

X = df_model[features]
y = df_model["delivery_time_hours"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFeatures:")
print(X.columns.tolist())

print("\nTarget:")
print(y.name)

X shape: (24745, 8)
y shape: (24745,)

Features:
['delivery_partner', 'package_type', 'vehicle_type', 'delivery_mode', 'region', 'weather_condition', 'distance_km', 'package_weight_kg']

Target:
delivery_time_hours

In [26]:
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()
numerical_features = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
['delivery_partner', 'package_type', 'vehicle_type', 'delivery_mode', 'region', 'weather_condition']

Numerical features:
['distance_km', 'package_weight_kg']

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (19796, 8)
X_test : (4949, 8)
y_train: (19796,)
y_test : (4949,)

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

print("Preprocessor created successfully.")

Preprocessor created successfully.

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

linear_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ]
)

linear_model.fit(X_train, y_train)

linear_predictions = linear_model.predict(X_test)

print("Linear Regression trained successfully.")

Linear Regression trained successfully.

In [30]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

linear_mae = mean_absolute_error(y_test, linear_predictions)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_predictions))
linear_r2 = r2_score(y_test, linear_predictions)

print("Linear Regression Results")
print("-------------------------")
print("MAE :", linear_mae)
print("RMSE:", linear_rmse)
print("R²  :", linear_r2)

Linear Regression Results
-------------------------
MAE : 1.3019769375050925
RMSE: 1.633251854836821
R²  : 0.717277045102714

In [31]:
from sklearn.tree import DecisionTreeRegressor

tree_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", DecisionTreeRegressor(random_state=42))
    ]
)

tree_model.fit(X_train, y_train)

tree_predictions = tree_model.predict(X_test)

print("Decision Tree trained successfully.")

Decision Tree trained successfully.

In [32]:
tree_mae = mean_absolute_error(y_test, tree_predictions)
tree_rmse = np.sqrt(mean_squared_error(y_test, tree_predictions))
tree_r2 = r2_score(y_test, tree_predictions)

print("Decision Tree Results")
print("--------------------")
print("MAE :", tree_mae)
print("RMSE:", tree_rmse)
print("R²  :", tree_r2)

Decision Tree Results
--------------------
MAE : 1.775308143059204
RMSE: 2.3305364796298367
R²  : 0.42433932623585147

In [33]:
from sklearn.ensemble import RandomForestRegressor

forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestRegressor(
                n_estimators=100,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

forest_model.fit(X_train, y_train)

forest_predictions = forest_model.predict(X_test)

print("Random Forest trained successfully.")

Random Forest trained successfully.

In [34]:
forest_mae = mean_absolute_error(y_test, forest_predictions)
forest_rmse = np.sqrt(mean_squared_error(y_test, forest_predictions))
forest_r2 = r2_score(y_test, forest_predictions)

print("Random Forest Results")
print("--------------------")
print("MAE :", forest_mae)
print("RMSE:", forest_rmse)
print("R²  :", forest_r2)

Random Forest Results
--------------------
MAE : 1.35150333400687
RMSE: 1.703572174333173
R²  : 0.692407439922295

In [35]:
results = {
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        linear_mae,
        tree_mae,
        forest_mae
    ],
    "RMSE": [
        linear_rmse,
        tree_rmse,
        forest_rmse
    ],
    "R2": [
        linear_r2,
        tree_r2,
        forest_r2
    ]
}

results_df = pd.DataFrame(results)

print(results_df)

               Model       MAE      RMSE        R2
0  Linear Regression  1.301977  1.633252  0.717277
1      Decision Tree  1.775308  2.330536  0.424339
2      Random Forest  1.351503  1.703572  0.692407

In [36]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    linear_model,
    X,
    y,
    cv=5,
    scoring="r2"
)

print("5-Fold Cross-Validation R² Scores:")
print(cv_scores)

print("Mean CV R²:", cv_scores.mean())
print("Standard Deviation:", cv_scores.std())

5-Fold Cross-Validation R² Scores:
[0.73378675 0.72953538 0.72074072 0.71949169 0.72641686]
Mean CV R²: 0.7259942802204155
Standard Deviation: 0.005353954352606339

In [37]:
forest_cv_scores = cross_val_score(
    forest_model,
    X,
    y,
    cv=5,
    scoring="r2"
)

print("5-Fold Cross-Validation R² Scores:")
print(forest_cv_scores)

print("Mean CV R²:", forest_cv_scores.mean())
print("Standard Deviation:", forest_cv_scores.std())

5-Fold Cross-Validation R² Scores:
[0.71256833 0.70958093 0.69944774 0.7002585  0.70605572]
Mean CV R²: 0.7055822430457462
Standard Deviation: 0.005118467745127139

In [38]:
cv_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest"
    ],
    "Mean CV R²": [
        cv_scores.mean(),
        forest_cv_scores.mean()
    ],
    "Std CV R²": [
        cv_scores.std(),
        forest_cv_scores.std()
    ]
})

print(cv_results)

               Model  Mean CV R²  Std CV R²
0  Linear Regression    0.725994   0.005354
1      Random Forest    0.705582   0.005118

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
param_grid = {
    "model__n_estimators": [50, 100, 150],
    "model__max_depth": [None, 10, 20],
    "model__min_samples_split": [2, 5]
}

print("Parameter grid created successfully.")

Parameter grid created successfully.

In [41]:
grid_search = GridSearchCV(
    estimator=forest_model,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

print("GridSearchCV created successfully.")

GridSearchCV created successfully.

In [42]:
grid_search.fit(X, y)

print("Hyperparameter tuning completed.")

Hyperparameter tuning completed.

In [44]:
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest Cross-Validation R²:")
print(grid_search.best_score_)

Best Parameters:
{'model__max_depth': 10, 'model__min_samples_split': 5, 'model__n_estimators': 100}

Best Cross-Validation R²:
0.7197606712669555

In [45]:
best_forest_model = grid_search.best_estimator_

tuned_forest_predictions = best_forest_model.predict(X_test)

tuned_forest_mae = mean_absolute_error(
    y_test,
    tuned_forest_predictions
)

tuned_forest_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        tuned_forest_predictions
    )
)

tuned_forest_r2 = r2_score(
    y_test,
    tuned_forest_predictions
)

print("Tuned Random Forest Results")
print("---------------------------")
print("MAE :", tuned_forest_mae)
print("RMSE:", tuned_forest_rmse)
print("R²  :", tuned_forest_r2)

Tuned Random Forest Results
---------------------------
MAE : 1.166436936349818
RMSE: 1.4537572412150481
R²  : 0.7760048922610538

In [46]:
final_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "Tuned Random Forest"
    ],
    "MAE": [
        linear_mae,
        tree_mae,
        forest_mae,
        tuned_forest_mae
    ],
    "RMSE": [
        linear_rmse,
        tree_rmse,
        forest_rmse,
        tuned_forest_rmse
    ],
    "R2": [
        linear_r2,
        tree_r2,
        forest_r2,
        tuned_forest_r2
    ]
})

print(final_results)

                 Model       MAE      RMSE        R2
0    Linear Regression  1.301977  1.633252  0.717277
1        Decision Tree  1.775308  2.330536  0.424339
2        Random Forest  1.351503  1.703572  0.692407
3  Tuned Random Forest  1.166437  1.453757  0.776005

In [47]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": linear_predictions
})

print(comparison.head(20))

    Actual  Predicted
0        5   6.833024
1        3   1.956189
2        5   3.914031
3       16  10.071751
4        5   6.030893
5        9   8.893196
6       10  10.576907
7       11   9.497896
8        6   4.549307
9        7   7.200657
10      10  10.867766
11       5   3.708825
12       8   8.996943
13       4   5.359792
14       5   7.111152
15       3   2.952729
16       4   5.051286
17       3   3.403740
18       8  10.472789
19       5   4.460568

In [48]:
comparison["Error"] = (
    comparison["Actual"] -
    comparison["Predicted"]
)

print(comparison.head(20))

    Actual  Predicted     Error
0        5   6.833024 -1.833024
1        3   1.956189  1.043811
2        5   3.914031  1.085969
3       16  10.071751  5.928249
4        5   6.030893 -1.030893
5        9   8.893196  0.106804
6       10  10.576907 -0.576907
7       11   9.497896  1.502104
8        6   4.549307  1.450693
9        7   7.200657 -0.200657
10      10  10.867766 -0.867766
11       5   3.708825  1.291175
12       8   8.996943 -0.996943
13       4   5.359792 -1.359792
14       5   7.111152 -2.111152
15       3   2.952729  0.047271
16       4   5.051286 -1.051286
17       3   3.403740 -0.403740
18       8  10.472789 -2.472789
19       5   4.460568  0.539432

In [49]:
print("Mean Error:", comparison["Error"].mean())
print("Mean Absolute Error:", comparison["Error"].abs().mean())

print("\nLargest absolute errors:")
print(
    comparison
    .assign(Absolute_Error=comparison["Error"].abs())
    .sort_values("Absolute_Error", ascending=False)
    .head(10)
)

Mean Error: -0.04610209614050282
Mean Absolute Error: 1.3019769375050925

Largest absolute errors:
      Actual  Predicted     Error  Absolute_Error
4425      19  12.317935  6.682065        6.682065
2673      17  10.950815  6.049185        6.049185
3         16  10.071751  5.928249        5.928249
764       18  12.421876  5.578124        5.578124
3819      14   8.535429  5.464571        5.464571
2372      17  11.701598  5.298402        5.298402
4051      17  11.774299  5.225701        5.225701
1633      13   7.846673  5.153327        5.153327
3281      16  10.894700  5.105300        5.105300
1869      14   8.906618  5.093382        5.093382

In [50]:
best_model = grid_search.best_estimator_

rf_model = best_model.named_steps["model"]
rf_preprocessor = best_model.named_steps["preprocessor"]

feature_names = rf_preprocessor.get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    "Importance",
    ascending=False
)

print(importance_df.head(15))

                                    Feature  Importance
39                   remainder__distance_km    0.609068
38    categorical__weather_condition_stormy    0.175129
37     categorical__weather_condition_rainy    0.112311
35     categorical__weather_condition_foggy    0.046805
40             remainder__package_weight_kg    0.018237
17       categorical__package_type_pharmacy    0.001324
21        categorical__vehicle_type_scooter    0.001323
30                categorical__region_north    0.001309
24       categorical__delivery_mode_express    0.001292
6       categorical__delivery_partner_fedex    0.001275
25      categorical__delivery_mode_same day    0.001271
22          categorical__vehicle_type_truck    0.001261
1   categorical__delivery_partner_blue dart    0.001255
18           categorical__vehicle_type_bike    0.001244
13    categorical__package_type_electronics    0.001238

In [51]:
tuned_comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": tuned_forest_predictions
})

tuned_comparison["Error"] = (
    tuned_comparison["Actual"] -
    tuned_comparison["Predicted"]
)

tuned_comparison["Absolute_Error"] = (
    tuned_comparison["Error"].abs()
)

print(tuned_comparison.head(20))

    Actual  Predicted     Error  Absolute_Error
0        5   6.831847 -1.831847        1.831847
1        3   2.167461  0.832539        0.832539
2        5   3.824538  1.175462        1.175462
3       16  10.946574  5.053426        5.053426
4        5   5.928851 -0.928851        0.928851
5        9   8.720962  0.279038        0.279038
6       10  10.290607 -0.290607        0.290607
7       11   9.809965  1.190035        1.190035
8        6   4.845020  1.154980        1.154980
9        7   6.911886  0.088114        0.088114
10      10  10.590709 -0.590709        0.590709
11       5   3.716523  1.283477        1.283477
12       8   8.913515 -0.913515        0.913515
13       4   5.387009 -1.387009        1.387009
14       5   6.911601 -1.911601        1.911601
15       3   2.873555  0.126445        0.126445
16       4   5.137970 -1.137970        1.137970
17       3   3.263651 -0.263651        0.263651
18       8   9.443707 -1.443707        1.443707
19       5   4.499741  0.500259        0.500259

In [52]:
print("Mean Error:", tuned_comparison["Error"].mean())
print("Mean Absolute Error:", tuned_comparison["Absolute_Error"].mean())

Mean Error: -0.03640158806913294
Mean Absolute Error: 1.166436936349818

In [53]:
print("\nLargest absolute errors:")

print(
    tuned_comparison
    .sort_values("Absolute_Error", ascending=False)
    .head(10)
)

Largest absolute errors:
      Actual  Predicted     Error  Absolute_Error
3244      13   7.838251  5.161749        5.161749
1633      13   7.924480  5.075520        5.075520
3         16  10.946574  5.053426        5.053426
764       18  13.261524  4.738476        4.738476
250       11   6.387558  4.612442        4.612442
1869      14   9.390622  4.609378        4.609378
516       13   8.414499  4.585501        4.585501
4425      19  14.450033  4.549967        4.549967
4308       5   9.459949 -4.459949        4.459949
1619      11   6.590467  4.409533        4.409533

In [54]:
within_1_hour = (
    tuned_comparison["Absolute_Error"] <= 1
).mean() * 100

print("Predictions within 1 hour:", within_1_hour, "%")

Predictions within 1 hour: 49.929278642149924 %

In [55]:
within_2_hours = (
    tuned_comparison["Absolute_Error"] <= 2
).mean() * 100

print("Predictions within 2 hours:", within_2_hours, "%")

Predictions within 2 hours: 82.96625580925439 %

In [58]:
weather_analysis = (
    df_model.groupby("weather_condition")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

weather_analysis

                   count      mean  median
weather_condition
stormy              4198  8.807527     9.0
rainy               4171  7.804843     8.0
foggy               4217  6.489685     6.0
clear               4025  4.893913     5.0
cold                4076  4.869480     5.0
hot                 4058  4.869394     5.0

In [60]:
df_model["distance_range"] = pd.cut(
    df_model["distance_km"],
    bins=[0, 5, 10, 20, 50, float("inf")],
    labels=["0–5 km", "5–10 km", "10–20 km", "20–50 km", "50+ km"],
    include_lowest=True
)

distance_analysis = (
    df_model.groupby("distance_range", observed=True)["delivery_time_hours"]
    .agg(["count", "mean", "median"])
)

distance_analysis

                count      mean  median
distance_range
0–5 km            310  2.900000     2.0
5–10 km           374  3.106952     3.0
10–20 km          785  3.110828     3.0
20–50 km         2377  3.461927     3.0
50+ km          20899  6.864874     7.0

In [61]:
vehicle_analysis = (
    df_model.groupby("vehicle_type")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

vehicle_analysis

              count      mean  median
vehicle_type
bike           4115  6.346294     6.0
scooter        4136  6.336557     6.0
van            4144  6.333012     6.0
ev van         4065  6.328413     6.0
ev bike        4168  6.271353     6.0
truck          4117  6.259412     6.0

In [62]:
delivery_mode_analysis = (
    df_model.groupby("delivery_mode")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

delivery_mode_analysis

               count      mean  median
delivery_mode
two day         6241  6.340010     6.0
same day        6197  6.327416     6.0
standard        6125  6.299592     6.0
express         6182  6.282271     6.0

In [64]:
region_analysis = (
    df_model.groupby("region")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

region_analysis

         count      mean  median
region
west      5041  6.363817     6.0
central   4997  6.362217     6.0
north     4899  6.312921     6.0
east      4879  6.264398     6.0
south     4929  6.256441     6.0

In [65]:
partner_analysis = (
    df_model.groupby("delivery_partner")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

partner_analysis

                  count      mean  median
delivery_partner
xpressbees         2800  6.382500     6.0
blue dart          2766  6.369125     6.0
ekart              2762  6.356626     6.0
shadowfax          2710  6.332472     6.0
amazon logistics   2690  6.328253     6.0
ecom express       2693  6.314148     6.0
dhl                2775  6.311351     6.0
delhivery          2758  6.217912     6.0
fedex              2791  6.200287     6.0

In [66]:
package_analysis = (
    df_model.groupby("package_type")["delivery_time_hours"]
    .agg(["count", "mean", "median"])
    .sort_values("mean", ascending=False)
)

package_analysis

                  count      mean  median
package_type
clothing           2742  6.462801     6.0
pharmacy           2778  6.407127     6.0
cosmetics          2718  6.350258     6.0
automobile parts   2761  6.340456     6.0
furniture          2718  6.279617     6.0
groceries          2676  6.267937     6.0
electronics        2766  6.245481     6.0
fragile items      2808  6.239672     6.0
documents          2778  6.219582     6.0

In [68]:
feature_importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": rf_model.feature_importances_
})

feature_importance_df

                                           feature  importance
0   categorical__delivery_partner_amazon logistics    0.001167
1          categorical__delivery_partner_blue dart    0.001255
2          categorical__delivery_partner_delhivery    0.001173
3                categorical__delivery_partner_dhl    0.001024
4       categorical__delivery_partner_ecom express    0.001169
5              categorical__delivery_partner_ekart    0.001084
6              categorical__delivery_partner_fedex    0.001275
7          categorical__delivery_partner_shadowfax    0.001010
8         categorical__delivery_partner_xpressbees    0.001071
9       categorical__package_type_automobile parts    0.001000
10              categorical__package_type_clothing    0.001054
11             categorical__package_type_cosmetics    0.001105
12             categorical__package_type_documents    0.001176
13           categorical__package_type_electronics    0.001238
14         categorical__package_type_fragile items    0.001086
15             categorical__package_type_furniture    0.000999
16             categorical__package_type_groceries    0.000956
17              categorical__package_type_pharmacy    0.001324
18                  categorical__vehicle_type_bike    0.001244
19               categorical__vehicle_type_ev bike    0.001169
20                categorical__vehicle_type_ev van    0.001141
21               categorical__vehicle_type_scooter    0.001323
22                 categorical__vehicle_type_truck    0.001261
23                   categorical__vehicle_type_van    0.001120
24              categorical__delivery_mode_express    0.001292
25             categorical__delivery_mode_same day    0.001271
26             categorical__delivery_mode_standard    0.001077
27              categorical__delivery_mode_two day    0.001060
28                     categorical__region_central    0.001238
29                        categorical__region_east    0.001035
30                       categorical__region_north    0.001309
31                       categorical__region_south    0.001144
32                        categorical__region_west    0.001120
33            categorical__weather_condition_clear    0.000159
34             categorical__weather_condition_cold    0.000170
35            categorical__weather_condition_foggy    0.046805
36              categorical__weather_condition_hot    0.000149
37            categorical__weather_condition_rainy    0.112311
38           categorical__weather_condition_stormy    0.175129
39                          remainder__distance_km    0.609068
40                    remainder__package_weight_kg    0.018237

In [69]:
def get_original_feature(feature):
    if feature.startswith("categorical__"):
        feature = feature.replace("categorical__", "", 1)
        return feature.split("_", 1)[0]
    elif feature.startswith("remainder__"):
        return feature.replace("remainder__", "", 1)
    return feature

feature_importance_df["original_feature"] = (
    feature_importance_df["feature"].apply(get_original_feature)
)

grouped_importance = (
    feature_importance_df
    .groupby("original_feature")["importance"]
    .sum()
    .sort_values(ascending=False)
)

grouped_importance

original_feature
distance_km          0.609068
weather              0.334723
package_weight_kg    0.018237
delivery             0.014928
package              0.009940
vehicle              0.007259
region               0.005846
Name: importance, dtype: float64

In [70]:
original_features = [
    "delivery_partner",
    "package_type",
    "vehicle_type",
    "delivery_mode",
    "region",
    "weather_condition",
    "distance_km",
    "package_weight_kg"
]

def get_original_feature(feature):
    for original in original_features:
        if original in feature:
            return original
    return feature

feature_importance_df["original_feature"] = (
    feature_importance_df["feature"].apply(get_original_feature)
)

grouped_importance = (
    feature_importance_df
    .groupby("original_feature")["importance"]
    .sum()
    .sort_values(ascending=False)
)

grouped_importance

original_feature
distance_km          0.609068
weather_condition    0.334723
package_weight_kg    0.018237
delivery_partner     0.010228
package_type         0.009940
vehicle_type         0.007259
region               0.005846
delivery_mode        0.004699
Name: importance, dtype: float64

In [72]:
prediction_analysis = pd.Series(tuned_forest_predictions).describe()

prediction_analysis

count    4949.000000
mean        6.349394
std         2.646160
min         1.405252
25%         4.328287
50%         6.320330
75%         8.114123
max        14.450033
dtype: float64

In [73]:
high_time_threshold = np.percentile(tuned_forest_predictions, 75)

high_time_mask = tuned_forest_predictions > high_time_threshold

high_time_count = high_time_mask.sum()
high_time_percentage = high_time_mask.mean() * 100

print("High predicted-time threshold:", high_time_threshold)
print("Number of high predicted-time deliveries:", high_time_count)
print("Percentage of test deliveries:", high_time_percentage)

High predicted-time threshold: 8.11412345195789
Number of high predicted-time deliveries: 1237
Percentage of test deliveries: 24.99494847443928

In [75]:
high_time_test = X_test.copy()

high_time_test["predicted_delivery_time"] = tuned_forest_predictions
high_time_test["high_time"] = high_time_test["predicted_delivery_time"] > high_time_threshold

high_time_summary = (
    high_time_test[high_time_test["high_time"]]
    .merge(
        df_model.loc[X_test.index, [
            "distance_km",
            "package_weight_kg",
            "weather_condition",
            "vehicle_type",
            "delivery_mode",
            "region"
        ]],
        left_index=True,
        right_index=True
    )
)

high_time_summary.head()

,delivery_partner,package_type,vehicle_type_x,delivery_mode_x,region_x,weather_condition_x,distance_km_x,package_weight_kg_x,predicted_delivery_time,high_time,distance_km_y,package_weight_kg_y,weather_condition_y,vehicle_type_y,delivery_mode_y,region_y
20574,blue dart,furniture,ev bike,express,central,rainy,246.1,44.03,10.946574,True,246.1,44.03,rainy,ev bike,express,central
5116,ekart,automobile parts,ev van,same day,east,rainy,195.4,37.28,8.720962,True,195.4,37.28,rainy,ev van,same day,east
4772,blue dart,electronics,ev van,express,north,stormy,216.9,5.18,10.290607,True,216.9,5.18,stormy,ev van,express,north
11572,amazon logistics,groceries,ev bike,two day,central,stormy,179.2,10.21,9.809965,True,179.2,10.21,stormy,ev bike,two day,central
14287,delhivery,clothing,truck,express,north,stormy,233.4,33.37,10.590709,True,233.4,33.37,stormy,truck,express,north

In [76]:
high_time_summary = high_time_summary[
    [
        "distance_km_y",
        "package_weight_kg_y",
        "weather_condition_y",
        "vehicle_type_y",
        "delivery_mode_y",
        "region_y",
        "predicted_delivery_time"
    ]
]

print("High predicted-time deliveries:")
print("Count:", len(high_time_summary))
print()

print("Average distance:", high_time_summary["distance_km_y"].mean())
print("Average package weight:", high_time_summary["package_weight_kg_y"].mean())
print("Average predicted delivery time:", high_time_summary["predicted_delivery_time"].mean())

High predicted-time deliveries:
Count: 1237

Average distance: 233.68827809215847
Average package weight: 25.67874696847211
Average predicted delivery time: 9.818420801675144

In [77]:
print("\nWeather distribution:")
print(high_time_summary["weather_condition_y"].value_counts())

print("\nDistance summary:")
print(high_time_summary["distance_km_y"].describe())

Weather distribution:
weather_condition_y
stormy    501
rainy     406
foggy     202
hot        52
clear      40
cold       36
Name: count, dtype: int64

Distance summary:
count    1237.000000
mean      233.688278
std        49.696768
min        60.500000
25%       195.300000
50%       242.200000
75%       278.000000
max       297.100000
Name: distance_km_y, dtype: float64

In [80]:
normal_time_summary = high_time_test[
    ~high_time_test["high_time"]
].merge(
    df_model.loc[X_test.index, [
        "distance_km",
        "package_weight_kg",
        "weather_condition"
    ]],
    left_index=True,
    right_index=True
)

print("Normal predicted-time deliveries:")
print("Count:", len(normal_time_summary))
print("Average distance:", normal_time_summary["distance_km_y"].mean())
print("Average package weight:", normal_time_summary["package_weight_kg_y"].mean())
print("Average predicted delivery time:",
      normal_time_summary["predicted_delivery_time"].mean())

Normal predicted-time deliveries:
Count: 3712
Average distance: 125.76214978448276
Average package weight: 25.411293103448276
Average predicted delivery time: 5.193363396466053

In [82]:
print("\nWeather distribution among normal predicted-time deliveries:")
print(normal_time_summary["weather_condition_y"].value_counts())

Weather distribution among normal predicted-time deliveries:
weather_condition_y
cold      801
hot       766
clear     741
foggy     604
rainy     426
stormy    374
Name: count, dtype: int64

In [84]:
weather_high_time = (
    high_time_test
    .groupby("weather_condition")["high_time"]
    .agg(["count", "sum"])
)

weather_high_time["high_time_percentage"] = (
    weather_high_time["sum"] / weather_high_time["count"] * 100
)

weather_high_time = weather_high_time.sort_values(
    "high_time_percentage",
    ascending=False
)

print(weather_high_time)

                   count  sum  high_time_percentage
weather_condition
stormy               875  501             57.257143
rainy                832  406             48.798077
foggy                806  202             25.062035
hot                  818   52              6.356968
clear                781   40              5.121639
cold                 837   36              4.301075